version: '3'

services:

  nginx:
    volumes:
      - certificates:/etc/letsencrypt
      - ./docker/nginx/conf/nginx.prod.conf:/etc/nginx/nginx.conf
    depends_on:
      - nodejs
      - certbot

  certbot:
    image: certbot/certbot
    volumes:
      - certificates:/etc/letsencrypt
      - ./frontend/public:/www
    entrypoint: sh -c 'certbot certonly --authenticator webroot -d listodo.ru --webroot-path /www --email ramirez2006@mail.ru --agree-tos --dry-run'

volumes:
  certificates:
