version: '3'

services:

  nginx:
    volumes:
      - certificates:/etc/letsencrypt
      - ./docker/nginx/conf/nginx.prod.conf:/etc/nginx/nginx.conf
    depends_on:
      - nodejs

  web-pushes:
    <<: *php
    command: sh -c 'php console webPushes'

  certbot:
    image: certbot/certbot
    volumes:
      - certificates:/etc/letsencrypt
      - ./frontend/public:/www
    entrypoint: sh -c 'certbot certonly --authenticator webroot -d listodo.ru -d app.listodo.ru --webroot-path /www --email ramirez2006@mail.ru --agree-tos --dry-run'
    # --dry-run for simulating

volumes:
  certificates:
