#!/usr/bin/env php
<?php

error_reporting(E_ALL);

require './vendor/autoload.php';

$request = \Laminas\Diactoros\ServerRequestFactory::fromGlobals();

try {
    (new \Framework\Http\Application(
        $request,
        new \Framework\Http\Middleware\PipelineConsole(),
        new \Framework\Http\Router\RouterConsole($request)
    ))->run();
} catch (\Throwable $exception) {
    echo "{$exception->getMessage()}\n";
}

